### ISSUE TITLE
question regarding the n_groups argument

### ISSUE THREAD

**Issue by fkrauer** [itsdfish/DifferentialEvolutionMCMC.jl#35]
Hey @itsdfish 

I have a question regarding the arguments of the DE object. What does the n_groups argument stand for? I understand that the standard recommendation is to have 2-3 times as many chains as parameters, which is set with Np. What does the n_groups argument do, is it related to block updating? The default is 4, which leads to 12 times as many chains as parameters. If, for the sake of speed, I wanted to reduce the number of chains, should I reduce Np or n_groups? TIA

**Comment by itsdfish** [comment]
Hello,

The algorithm I implemented is based the following paper: [Approximate Bayesian computation with differential evolution](https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.1063.652&rep=rep1&type=pdf)

Rather than using a single group of particles, this algorithm uses multiple groups of particles. Particles within each group can be exchanged in a migration step. So you increase the number of chains (or particles) by changing either parameter. I'm not sure which option you should reduce. Groups are multithreaded. So that may not speed up the samples much if `n_groups` is less than the number of processors on your machine.

I would recommend trying different configurations with `KDE_Example.jl` because it requires about 30 seconds to finish, which is not too fast to extrapolate to your slower model.

**Comment by itsdfish** [comment]
Setting Np=6,  I obtained the following results with KDE_Example.jl

n_groups = 1 : 18 seconds
n_groups  = 2 : 19 seconds
n_groups  = 3 : 23 seconds
n_groups  = 4 : 29 seconds

There is a gradual slow down with the number of groups even though they were executed in parallel. One reason for the slow down is likely overhead. Another reason is that each iteration is only as fast as the slowest group. As more groups are added, the speed of the slowest group will decrease on average. Finally, once all of my cores were in use, there was a tradeoff between the sampler and other programs running on my computer. So you might get a small speed up by setting n_groups = number of cores - 1. 

If you decide the decrease the number of particles per group (Np), it may be a good idea to consider the effective sample size per second instead of seconds.  The sampler might become inefficient if Np is decreased too much.

**Comment by fkrauer** [comment]
ah yes, thanks for the link and the benchmarks. Wasn't aware this is an ABC DE. I am doing some benchmarking with my model. I found the same thing: n_groups = number of cores - 1 seems to be the good choice.

**Comment by itsdfish** [comment]
No problem. I should have clarified earlier. The sampler does not use ABC, but does use many aspects of the DE variant in the paper. I tried the ABC approach described in the paper, but it does not work well with many models. If the statistics in the simulated data are not sufficient, the posterior distributions are usually wrong. What I found to work better in cases where a likelihood function is not known is to approximate it with a kernel density function (as in KDE_Example.jl).

**Comment by fkrauer** [comment]
ah right that makes more sense, the ABC thing confused me. There is also a modified variant of the DE with a snooker update, which allows to have a reduced set of chains https://link.springer.com/article/10.1007/s11222-008-9104-9. It seems to be more efficient than the standard DE MCMC. It worked very well for me in the past for complex models/likelihood landscapes.

**Comment by itsdfish** [comment]
I started to add that new algorithm a while back on a different branch, but I could not figure how it worked exactly. I hope to revisit it in the future.

**Comment by fkrauer** [comment]
ah nice. If you are interested, check out the source code for the BayesianTools package (R code but I am sure you are familiar). They have various MCMC including the DE and the DE with the snooker update (DEzs), as well as further variants DE with adaptive metropolis (DREAM and DREAMzs).
